# Generated by Django 4.0.4 on 2022-04-30 03:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("wiki_title", models.CharField(default="Unknown", max_length=500)),
                (
                    "target_lang",
                    models.CharField(
                        choices=[
                            ("bn", "Bengali"),
                            ("gu", "Gujarati"),
                            ("hi", "Hindi"),
                            ("kn", "Kannada"),
                            ("ml", "Malayalam"),
                            ("mr", "Marathi"),
                            ("ne", "Nepali"),
                            ("or", "Oriya"),
                            ("pa", "Panjabi"),
                            ("si", "Sinhala"),
                            ("ta", "Tamil"),
                            ("te", "Telugu"),
                            ("ur", "Urdu"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ("-modified_on", "-created_on"),
            },
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("original_sentence", models.TextField(blank=True)),
                ("translated_sentence", models.TextField(blank=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worker.project"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_on",),
            },
        ),
    ]
