# Generated by Django 4.0.4 on 2022-04-30 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("worker", "0002_project_accessible_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="accessible_to",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
