# Generated by Django 4.0.4 on 2022-04-30 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("worker", "0003_alter_project_accessible_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="accessible_to",
        ),
        migrations.AddField(
            model_name="project",
            name="accessible_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
