# Generated by Django 4.0.4 on 2022-05-04 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("worker", "0004_remove_project_accessible_to_project_accessible_to"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentence",
            options={"ordering": ("created_on",)},
        ),
        migrations.AddField(
            model_name="sentence",
            name="accessible_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
